const readSchemas = require('./utils');

function getSidebars(rootDir) {
    const schemas = readSchemas(rootDir);
    const sidebars = {};

    for (let key in schemas) {
        sidebars[key] = [{ type: 'autogenerated', dirName: key }];
    }

    return sidebars;
}

module.exports = getSidebars;
