const { readSchemas } = require('./index.js');

function getSidebars() {
    const schemas = readSchemas();
    const sidebars = {};

    for (let key in schemas) {
        sidebars[key] = [{ type: 'autogenerated', dirName: key }];
    }

    return sidebars;
}

module.exports = getSidebars();
